create table role (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id))
create table user_roles (users_id bigint not null, roles_id bigint not null, primary key (users_id, roles_id))
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role
alter table user_roles add constraint FK7ecyobaa59vxkxckg6t355l86 foreign key (users_id) references user
create table role (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id))
create table user_roles (users_id bigint not null, roles_id bigint not null, primary key (users_id, roles_id))
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role
alter table user_roles add constraint FK7ecyobaa59vxkxckg6t355l86 foreign key (users_id) references user
create table role (id bigint generated by default as identity, name varchar(255) not null, primary key (id))
create table user (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id))
create table user_roles (users_id bigint not null, roles_id bigint not null, primary key (users_id, roles_id))
create table wishlist (id bigint generated by default as identity, create_date timestamp, name varchar(255), owner_id bigint, primary key (id))
create table wishlist_element (id bigint generated by default as identity, create_date timestamp, name varchar(255), price integer, owner_wishlist_id bigint, primary key (id))
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role
alter table user_roles add constraint FK7ecyobaa59vxkxckg6t355l86 foreign key (users_id) references user
alter table wishlist add constraint FKiopaxy8rxixtjvh7w84qkt3gg foreign key (owner_id) references user
alter table wishlist_element add constraint FKaakjkbhs83yhkqe2l0bgsde91 foreign key (owner_wishlist_id) references wishlist
INSERT INTO "PUBLIC"."USER" VALUES (0, '$2a$10$OXWRzKsQ6agsdjkv406SPOO7z9rvglmeyxs6si/oyIxPSv9gD2Aly', 'adminbacsi')
INSERT INTO "PUBLIC"."ROLE" VALUES (0, 'ADMIN'), (1, 'USER')
INSERT INTO "PUBLIC"."USER_ROLES" VALUES (0,0)
COMMIT
