INSERT INTO "PUBLIC"."USER" VALUES (0, '$2a$10$OXWRzKsQ6agsdjkv406SPOO7z9rvglmeyxs6si/oyIxPSv9gD2Aly', 'adminbacsi');
INSERT INTO "PUBLIC"."ROLE" VALUES (0, 'ADMIN'), (1, 'USER');
INSERT INTO "PUBLIC"."USER_ROLES" VALUES (0,0);
COMMIT;